##########
# collectionbuilder-csv
# Jekyll Digital Collection Generator
# https://github.com/CollectionBuilder/collectionbuilder-csv
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: https://thecdil.github.io
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: /peoples-ipnw
# location of code, the full url to your github repository
source-code: https://github.com/thecdil/peoples-ipnw

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Peoples' Guide to the Inland Pacific Northwest
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: SUBTITLE HERE
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "This digital Peoples' Guide seeks to fill in the gaps by drawing attention inland from the coast to feature the rich histories and diverse peoples through short place stories from throughout the Interior Pacific Northwest region of North America." 

# keywords, a short list of subjects describing the collection, separated by semicolon, to appear in rich markup
keywords: idaho; history; inland northwest
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Alyssa Kreikemeier

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the CSV file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: ipnw-atlas
# page generation settings [optional!]
# [optional: only used if you need to tweak CB defaults or generate from more than one data file]
# page_gen:
#   - data: 'demo-metadata'
#     template: 'item'
#     name: 'objectid'
#     dir: 'items'
#     extension: 'html' 
#     filter: 'objectid'  

# activate collection
collections:
  essays:
    output: false


##########
# ORGANIZATION SETTINGS
#
# Enter name and link for your organization (replacing the name and links below)
# These values will be used in attribution and data 
organization-name: "Center for Digital Inquiry and Learning (CDIL)"
organization-link: https://cdil.lib.uidaho.edu/
# Add logo image links if you would like them to appear in banner and footer. Delete or leave blank to remove logos.
organization-logo-banner: https://www.lib.uidaho.edu/collectionbuilder/cdil-black.png
organization-logo-nav: https://www.lib.uidaho.edu/collectionbuilder/cdil-white.png

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# Library directory location. This allows you to customize where the standard assets are found.
# provide a relative path in this repository or full url 
lib-assets: /assets/lib
# ignore stuff
exclude: [docs/, Rakefile, rakelib/, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md]
# compress CSS output
sass:
  style: compressed
